### ISSUE TITLE
automated testing?

### ISSUE THREAD

**Issue by noci2012** [paulc/dnslib#12]
Is automated testing feasable?
That would verifying if the library works in various python versions simpler i guess.

It is one of the hurdles to keep it in gentoo.
Ref: https://bugs.gentoo.org/show_bug.cgi?id=718762

**Comment by paulc** [comment]
There is already an automated testing script which tests against multiple versions of python (see `run_tests.sh`)

Also if you look in `.github/workflows/test.yml` there is a set of automated CI tests which run on each commit (essentially the same as `run_tests.sh`)

**Comment by noci2012** [comment]
thanks, i added it to the gentoo bugzilla.
