### ISSUE TITLE
Request: add NULL to QTYPE

### ISSUE THREAD

**Issue by DidierStevens** [paulc/dnslib#14]
Would you mind adding the null record (experimental)?

in dnslib.QTYPE, add 10:'NULL'

I need it in one of my Python tools. I added it on my machine, but it would be easier for maintenance if it was in the master code.

Thanks,

Didier

**Comment by paulc** [comment]
Didier,

Thanks for pointing this out - I've added in Git but haven't created a new PyPi release yet (will wait until I have a few more changes). Hope this is ok.

Regards, Paul

**Comment by DidierStevens** [comment]
Thanks a lot Paul.

No problem, there's no hurry.

Cheers,

Didier
