### ISSUE TITLE
Accessing request ip in resolve()

### ISSUE THREAD

**Issue by brunobg** [paulc/dnslib#15]
Is it possible to get the request IP in `resolve()`? The use case is that I'm running a small DNS server for a domain, and I noticed it's being used as a full DNS server by somebody. I want to resolve any requests to *.mydomain.com for any IP except for a whitelist.

**Comment by stel-la** [comment]
`handler.client_address[0]` should do the job, assuming it's layed out like `resolve(self, request, **handler**):`
