### ISSUE TITLE
DNSLabels are not hashed case-insensitively

### ISSUE THREAD

**Issue by Tugzrida** [paulc/dnslib#22]
I'm not sure if there's a reason behind this, but the `__eq__` method of DNSLabel allows for case-insensitive comparison, whereas `__hash__`, `matchSuffix` and `stripSuffix` are case sensitive.

My use case is storing some records in a dict keyed by name and to get it to work properly now requires manually converting everything to lowercase before searching.

**Comment by paulc** [comment]
That's a good point -  Need to think about `matchSuffix` and `stripSuffix` but `hash` should definitely be case-insensitive. Fixed in 0.9.15

**Comment by antonio-salguero** [comment]
@paulc  wanted to ask what the status of matchSuffix is, will there also be a fix here ?

**Comment by caspChristian** [comment]
I just got an issue with matchSuffix as well.
I belive that it (at least most of the time) should be case insensitive https://datatracker.ietf.org/doc/html/rfc4343

example
```python
import unittest
from dnslib.dns import DNSRecord


class TestDNSRecord(unittest.TestCase):
    def test_caseInsensitiveMatchSuffix(self):
        q = DNSRecord.question("test.example.Com", "ANY")
        self.assertTrue(q.q.qname.matchSuffix("example.Com"))
        self.assertTrue(q.q.qname.matchSuffix("example.com"))
```

It is seen in the wild that requests are coming in especially as `.ip6.arpa.` and `.IP6.ARPA.`

**Comment by NiKiZe** [comment]
I just got an issue with matchSuffix as well.
I belive that it (at least most of the time) should be case insensitive https://datatracker.ietf.org/doc/html/rfc4343

example
```python
import unittest
from dnslib.dns import DNSRecord


class TestDNSRecord(unittest.TestCase):
    def test_caseInsensitiveMatchSuffix(self):
        q = DNSRecord.question("test.example.Com", "ANY")
        self.assertTrue(q.q.qname.matchSuffix("example.Com"))
        self.assertTrue(q.q.qname.matchSuffix("example.com"))
```

It is seen in the wild that requests are coming in especially as `.ip6.arpa.` and `.IP6.ARPA.`
