### ISSUE TITLE
How do I update dns dynamically?

### ISSUE THREAD

**Issue by wawan-ikhwan** [paulc/dnslib#38]
I used to update dns manually with using ```nsupdate``` command with ```bind9``` as DNS Server

Now I'm succeed using DNS Server/Client with this library, thank you so much.

I'm wonder should I make my own algorithm or own program,
or there is **already** feature in this library?

In ```nsupdate``` command, there was ```update section``` instead of addition section nor answer section. So there's special section to update like that, but that **readme.me** didn't mention it. Instead, it mention DNSSec which it's one component for updating?

**Comment by paulc** [comment]
This library only provides encoding/decoding - you need to implement this in your application
