### ISSUE TITLE
get full reqested url 

### ISSUE THREAD

**Issue by H1-N1** [paulc/dnslib#40]
hi!
how to log full url ex: www.exemple.com/ne/query.php?q=xxxx&u=xxxx

**Comment by NiKiZe** [comment]
You don't.
Only the hostname is used for DNS lookup.

You need to understand network basics, and difference between host part of URL, and full part of URL, and which part is where.

**Comment by H1-N1** [comment]
Thx for repley.
I dont need it for dns lookup 
I just need to log full url for investigation malwar traffic
If you can help with me that well be great 👍

**Comment by NiKiZe** [comment]
You are using this lib to do something? What? Show your code?

But again this does DNS, not http, you won't have URLs in DNS lookups, you claim you don't use it for lookups but then what are you using it for?

Also GitHub issues are for reporting issues. Not to get support on how to code. Use stackoverflow or other sites for that.

**Comment by H1-N1** [comment]
> You are using this lib to do something? What? Show your code?
> 
> But again this does DNS, not http, you won't have URLs in DNS lookups, you claim you don't use it for lookups but then what are you using it for?
> 
> Also GitHub issues are for reporting issues. Not to get support on how to code. Use stackoverflow or other sites for that.

You fk talk arrogant go to hell ps of s
