### ISSUE TITLE
Distribute wheels

### ISSUE THREAD

**Issue by samuelcolvin** [paulc/dnslib#42]
Hi, thanks for dnslib, it's great.

It would be great if dnslib could upload wheels to pypi to speedup install and also make the library available on more platforms.

Is this something you'd be interested in supporting?

**Comment by paulc** [comment]
Hi,

I've uploaded wheels for 0.9.20 (setup.py bdist_wheel / twine upload) which seems to work - to be honest I've slightly lost touch with Python packaging (I don't really use Python that much any more) so not sure if this is all I need to to. Could you let me know if this works for you?

Thanks, Paul

**Comment by samuelcolvin** [comment]
Thanks so much.

Without looking in detail (I'm on my phone), that looks correct.

Of course, if you wanted to do everything in the modern and correct way, there's lots more that could be done like switching to pyproject.toml and adding type hints, but on this specific request, it looks great.

Closing this, thanks again.
