### ISSUE TITLE
Rename README to README.md?

### ISSUE THREAD

**Issue by rmbolger** [paulc/dnslib#48]
Is there any reason not to rename README to README.md so it would get rendered nicely by the Github page renderer?

**Comment by NiKiZe** [comment]
Have you tried the rename and verified the result? If it looks good make a PR?

**Comment by rmbolger** [comment]
PR #49 submitted. Here's how it looks in my fork.

https://github.com/rmbolger/dnslib/tree/readme-rename

**Comment by paulc** [comment]
Added symlink
