### ISSUE TITLE
DNAME records are broken

### ISSUE THREAD

**Issue by nss-csis** [paulc/dnslib#50]
DNAME records are broken as this example shows:
![example_2_done](https://user-images.githubusercontent.com/43370352/204533047-6d6bcfad-bfa0-4c80-9ef1-7a99493cc440.png)

To compare here is the result from `dig`:
![example_1_done](https://user-images.githubusercontent.com/43370352/204533117-eff21358-1537-44e4-9494-d3f621ecfe97.png)

I think it is a matter of `DNAME` missing from `RDMAP`. Should I open a PR to fix it?

**Comment by SkySai1** [comment]
In parse method of dnslib there is limited rtype for parsing, the others is hexing via binascii.hexlify(data) and bring back in HEXDUMP format.
To fix it you need to unhex gated data with binascii.**un**hexlify(data)

P.S.
\# - specify HEXDUMP format
18 - length of origin data in bytes
0A636<...>756B00 - the hexdump

**Comment by paulc** [comment]
At the moment we don't decode the DNAME rdata (which is why you get the generic hexdump output). The logic for DNAME substitution is pretty complex (see https://www.rfc-editor.org/rfc/rfc6672.html) - if anyone wants to volunteer a PR I'd be happy to merge this.
