### ISSUE TITLE
DNSRecord parse failing, when DNS over TCP is used.

### ISSUE THREAD

**Issue by mai1x9** [paulc/dnslib#53]
When dns payload is sent over TCP (possibly DNS over HTTPS or it could be DNS over TCP when response is large), the data payload extracted from TCP protocol and passed to `DNSRecord.parse()` throws error related to parsing of data where data is not available when offset is set.

**Comment by paulc** [comment]
I'm going to close this as there is no way to reproduce - if you can provide a test case happy to have a look.
