### ISSUE TITLE
Bimap to Enum

### ISSUE THREAD

**Issue by jack60612** [paulc/dnslib#55]
Hello, I was wondering if you would be open to using Enum instead of Bimap? I will happily make a PR if you are open to the change.

**Comment by paulc** [comment]
That would probably be sensible (Bimap was a hack before Enums were supported) but I would want to bundle with a broader release which dropped support for Python 2 & Python <3.7 (see comments on Issue #56)

**Comment by nhairs** [comment]
nit: I feel like this issue should also be left open - @paulc 

Looking at the code I'm not sure how easy it will be to replace `Bimap` with `enum.IntEnum`. Specifically, I'm not sure if the `Bimap` fallback behaviour is replicated with an enum.

That said if we can make it work it would be good to use more "standard" components.

**Comment by nhairs** [comment]
@jack60612 - you might be interested in checking out my [typing](https://github.com/nhairs/dnslib/tree/typing) branch (PR #61). It might serve as a good base if you do want to try switching to Enum.

**Comment by jack60612** [comment]
> @jack60612 - you might be interested in checking out my [typing](https://github.com/nhairs/dnslib/tree/typing) branch (PR #61). It might serve as a good base if you do want to try switching to Enum.

i think i ended up just working with it but thanks for the offer!
