### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by anpic** [paulc/dnslib#69]
How do I get lookups through DNS servers with IPv6 public addresses?

domain = "github.com"
q = DNSRecord.question(domain, qtype = "AAAA")
p = q.send("2001:4860:4860::8888", ipv6 = True)

File .../dnslib/dns.py in send
    sock.sendto(self.pack(),(dest,port))
OSError: [Errno 101] Network is unreachable

**Comment by anpic** [comment]
maybe there is a similar case here
https://github.com/aio-libs/aiohttp/issues/5112

**Comment by paulc** [comment]
You don't have an IPv6 network connection
