### ISSUE TITLE
Problems handing out large replies

### ISSUE THREAD

**Issue by danhanks** [paulc/dnslib#71]
In dnslib/server.py, line 169, we have the following for TCP replies: 
```
rdata = struct.pack("!H",len(rdata)) + rdata
```
This is problematic for replies larger than 65k bytes as the max len(rdata) that can be packed is an unsigned short since we're using the 'H' format character.

Some TCP replies may need to exceed this length (e.g., axfr replies for large zones). Possible this could be expanded, or perhaps parameterized?

Thanks for consideration.

**Comment by nhairs** [comment]
Hi @danhanks,

According to [RFC1035](https://datatracker.ietf.org/doc/html/rfc1035#section-4.2.2) TCP DNS packets use a 16bit integer to represent the length of the packet. Unless there is an updated spec that I am not aware of this should not be changed as it will break the protocol.

**Comment by danhanks** [comment]
@nhairs Understood. I'm trying to send a response with rdata longer than 65k from a TCP DNServer, and running into this from dnslib/server.py, line 169 as mentioned above:
```
struct.error: 'H' format requires 0 <= number <= 65535
```
Any suggestions for this use case?

**Comment by nhairs** [comment]
After some searching I can't see any spec compatible way for sending DNS  messages over TCP which are larger than 2^16.

However, [based on my reading](https://en.wikipedia.org/wiki/DNS_zone_transfer), Zone Transfers (AXFR) avoid this constraint as they don't have to transfer the zone in a single message:

> The actual data transfer process begins by the client sending a query (opcode 0) with the special query type AXFR (value 252) over the TCP connection to the server. [...] The server responds with a series of response messages, comprising all of the resource records for every domain name in the "zone". The first response comprises the SOA resource record for the zone apex. The other data follows in no specified order. The end of the data is signaled by the server repeating the response containing the SOA resource record for the zone apex.

**Comment by paulc** [comment]
Thanks to Nick for the response - as he states the RFC specifies a 16 bit length. The protocol isn’t really designed for large transfers so I’d suggest that you think about another way to send the data - possibly send a one time URL to access the data?
